check:
  build: .
  net: host

riemann:
  image: rlister/riemann
  net: host
  ports:
    - "5555:5555"
    - "5555:5555/udp"
    - "5556:5556"
  volumes:
    - config:/app/etc

riemanndash:
  image: davidkelley/riemann-dash
  net: host
  ports:
    - "4567:4567"
